version: '3'
services:
  docker-challenge:
    image: shrikant1217/hive-ai:docker-issue-fixed
    ports:
      - "8080:8080"

  metrics-scraper:
    build:
      context: .
      dockerfile: Dockerfile.metrics
    ports:
      - "5000:5000"

